version: "3.8"

services:
  #################################################
  # 1) A Flask API (web) szolgáltatás
  #################################################
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spam_detector_api
    # Bár a Dockerfile-ban már van CMD, itt is expliciten megadhatjuk:
    command: ["python", "app/app.py"]
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs          # A konténer logjai a host ./logs-ba kerülnek
      - ./artifacts:/usr/src/app/artifacts
      - ./data:/usr/src/app/data
    environment:
      FLASK_ENV: production
      PORT: "5000"
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped

  #################################################
  # 2) A Trainer (train.py) szolgáltatás
  #################################################
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spam_trainer
    working_dir: /usr/src/app
    command: ["python", "train.py"]
    volumes:
      - ./data:/usr/src/app/data
      - ./artifacts:/usr/src/app/artifacts
      - ./logs:/usr/src/app/logs
    environment:
      PYTHONUNBUFFERED: "1"
    # Csak akkor indul, ha explicit megadod a „training” profilt:
    profiles:
      - training
    restart: "no"
